# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: ['main'] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # git 소스 체크아웃
      - name: git checkout
        uses: actions/checkout@v3
        
      - name: setup node
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 20.x

      - name: generate .env file
        run: |
          touch .env.production
          echo "${{ secrets.PRODUCTION_ENV }}" >> .env.production
          cat .env.production
      
      - name: npm install
        run: npm install
        
      - name: npm build
        run: npm run build:prod
        env:
          CI: false
      
      - name: deploy s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:
          # sync: 변경된 파일만 / --delete : 원본경로에서 삭제시 타깃에서도 삭제 
          aws s3 sync --delete --region ap-northeast-2 build s3://${{ secrets.AWS_BUCKET_NAME }}

      # - name: Invalidate CloudFront Cache
      #   run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"

      - name: CloudFront Invalidation
        env:
          CLOUD_FRONT_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUD_FRONT_ID --paths /*